import { NgModule } from '@angular/core';

import {
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule, MatFormFieldModule, MatExpansionModule, MatAutocompleteModule, MatButtonToggleModule, MatChipsModule,
    MatCheckboxModule, MatGridListModule, MatInputModule, MatListModule, MatProgressBarModule, MatProgressSpinnerModule,
    MatRippleModule, MatRadioModule, MatSelectModule, MatTooltipModule, MatSnackBarModule, MatSlideToggleModule,
    MatSliderModule, MatSidenavModule, MatTabsModule, MatDialogModule, MatDatepicker, MatDatepickerModule,
    MatNativeDateModule
} from '@angular/material';

@NgModule({
    imports: [
        MatAutocompleteModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatChipsModule,
        MatCheckboxModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatDialogModule,
        MatDatepickerModule
    ],
    exports: [
        MatAutocompleteModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatChipsModule,
        MatCheckboxModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
    ]
})
export class MaterialModule {}
