version: '2'
services:
    futeka-app:
        image: futeka
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://futeka-postgresql:5432/Futeka
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    futeka-postgresql:
        extends:
            file: postgresql.yml
            service: futeka-postgresql
